### ISSUE TITLE
Log MBAM TAP Messages in (custom) Eventlog for integration in Systems Management infrasatructures

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/MBAM-Test-Automation#8]
As describes - for better integration in systems management infrastucture log all entries (Info, Warning, Error) in a custom Eventlog. 

For systems management tools like SCOM or other ones this will lead to a better integration in alerting, e.g.

**Comment by devesly** [comment]
Implemented in MBAM TAP version 2
